name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        # Service containers to run with `runner-job`
        services:
            # Label used to access the service container
            postgres:
                # Docker Hub image
                image: postgres
                # Provide the password for postgres
                env:
                    POSTGRES_PASSWORD: qrlew-test
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    # Maps tcp port 5432 on service container to the host
                    - 5432:5432

        steps:
            - uses: actions/checkout@v3
            - name: Debug Docker
              run: docker ps
                docker network ls
                docker volume ls
                # Add more relevant Docker commands to help debug the issue

            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
