name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        # # Service containers to run with `runner-job`
        # services:
        #     # Label used to access the service container
        #     postgres:
        #         # Docker Hub image
        #         image: postgres
        #         # Provide the password for postgres
        #         env:
        #             POSTGRES_PASSWORD: qrlew-test
        #         # Set health checks to wait until postgres has started
        #         options: >-
        #             --health-cmd pg_isready
        #             --health-interval 10s
        #             --health-timeout 5s
        #             --health-retries 5
        #         ports:
        #             # Maps tcp port 5432 on service container to the host
        #             - 5432:5432

        steps:
            - uses: actions/checkout@v3

            # - name: Debug Docker
            #   run: |
            #     docker ps -a
            #     docker network ls
            #     docker volume ls
            #     CONTAINER_NAME=$(docker ps --filter "ancestor=postgres" --format "{{.Names}}")
            #     echo "Container Name: $CONTAINER_NAME"
            #     docker exec -i "$CONTAINER_NAME" psql -U postgres -h localhost -c "SELECT datname FROM pg_database;"

            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
