name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Debug Docker
              run: |
                docker ps -a
                docker network ls
                docker volume ls
                CONTAINER_NAME=$(docker ps --filter "ancestor=postgres" --format "{{.Names}}")
                echo "Container Name: $CONTAINER_NAME"
                docker exec -i "$CONTAINER_NAME" psql -U postgres -h localhost -p 5432 -c "SELECT datname FROM pg_database;"
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
